### ISSUE TITLE
[Transaction Stream Service] Consumer thread timed out waiting for transactions

### ISSUE THREAD

**Issue by fenghaojiang** [aptos-labs/aptos-indexer-processors#211]
## Description
I ran 4 indexers for about 24 hours and suddenly all indexers stopped for the same reason. 
Here are logs.
I wonder if it because the indexer catch up with the blockchain data stream so it would wait for the pending transaction. Are there solutions or How can I improve the situation? 

```shell
{"timestamp":"2023-12-06T22:05:32.961814Z","level":"ERROR","fields":{"message":"[Parser] Consumer thread timed out waiting for transactions","processor_name":"events_processor","service_type":"processor","stream_address":"https://grpc.mainnet.aptoslabs.com/"},"filename":"processor/src/worker.rs","line_number":254,"threadName":"tokio-runtime-worker","threadId":"ThreadId(31)"}
details = """
panicked at processor/src/worker.rs:261:33:
[Parser] Consumer thread timed out waiting for transactions"""
backtrace = """
   0:     0x556c727026df - backtrace::capture::Backtrace::new::hd3812181ba95c132
   1:     0x556c7245768d - server_framework::setup_panic_handler::{{closure}}::h711d03b7c65fe6a8
   2:     0x556c727d2041 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h87b887549356728a
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2021:9
                           std::panicking::rust_panic_with_hook::hd2f0efd2fec86cb0
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:735:13
   3:     0x556c727d1d76 - std::panicking::begin_panic_handler::{{closure}}::h3651b7fc4f61d784
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:601:13
   4:     0x556c727d0836 - std::sys_common::backtrace::__rust_end_short_backtrace::hbc468e4b98c7ae04
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:170:18
{"timestamp":"2023-12-06T22:05:32.970661Z","level":"ERROR","fields":{"message":"details = \"\"\"\npanicked at processor/src/worker.rs:261:33:\n[Parser] Consumer thread timed out waiting for transactions\"\"\"\nbacktrace = \"\"\"\n   0:     0x556c727026df - backtrace::capture::Backtrace::new::hd3812181ba95c132\n   1:     0x556c7245768d - server_framework::setup_panic_handler::{{closure}}::h711d03b7c65fe6a8\n   2:     0x556c727d2041 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h87b887549356728a\n                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2021:9\n                           std::panicking::rust_panic_with_hook::hd2f0efd2fec86cb0\n                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:735:13\n   3:     0x556c727d1d76 - std::panicking::begin_panic_handler::{{closure}}::h3651b7fc4f61d784\n                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:601:13\n   4:     0x556c727d0836 - std::sys_common::backtrace::__rust_end_short_backtrace::hbc468e4b98c7ae04\n                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:170:18\n   5:     0x556c727d1b12 - rust_begin_unwind\n                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5\n   6:     0x556c71bc9a45 - core::panicking::panic_fmt::h979245e2fdb2fabd\n                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14\n   7:     0x556c71c93d44 - processor::worker::Worker::run::{{closure}}::h19de3b3f89ff5ffc\n   8:     0x556c71c98185 - <processor::config::IndexerGrpcProcessorConfig as server_framework::RunnableConfig>::run::{{closure}}::h8bbc3ac6bcee62e5\n   9:     0x556c71c4d2a6 - <server_framework::GenericConfig<T> as server_framework::RunnableConfig>::run::{{closure}}::haa0bd3010848fb0d\n  10:     0x556c71c0f204 - server_framework::run_server_with_config::{{closure}}::{{closure}}::h6cffb61b76fb2233\n  11:     0x556c71c16fb2 - tokio::runtime::task::core::Core<T,S>::poll::h8d5ddcd038853453\n  12:     0x556c71c092e1 - tokio::runtime::task::harness::Harness<T,S>::poll::h966f7a06296c5172\n  13:     0x556c726d7c83 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h17a683d38fccdde5\n  14:     0x556c726d6ece - tokio::runtime::scheduler::multi_thread::worker::Context::run::h8c6e9db5df5b45de\n  15:     0x556c726dbf87 - tokio::runtime::context::scoped::Scoped<T>::set::hc23f308f5e1aa780\n  16:     0x556c726dbd6f - tokio::runtime::context::runtime::enter_runtime::hcd2bb531c72feab2\n  17:     0x556c726d63d8 - tokio::runtime::scheduler::multi_thread::worker::run::hcb889eaa62e3b5f1\n  18:     0x556c726c4a44 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h39e0ae4677314b1e\n  19:     0x556c726c6f59 - tokio::runtime::task::core::Core<T,S>::poll::hfb344e9dfb31bff4\n  20:     0x556c726c241f - tokio::runtime::task::harness::Harness<T,S>::poll::h86b8fbee4d959ecd\n  21:     0x556c726cb048 - tokio::runtime::blocking::pool::Inner::run::hcd49f282b0f4fc87\n  22:     0x556c726e1d45 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbf1640dcb5dd63fa\n  23:     0x556c726bea19 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h56f286b7e5210c94\n  24:     0x556c727d4c25 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfa37c25e0ad051b0\n                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2007:9\n                           <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9486bed8ab2e65ad\n                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2007:9\n                           std::sys::unix::thread::Thread::new::thread_start::hd28b46dbf5673d17\n                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys/unix/thread.rs:108:17\n  25:     0x7fd3af9deea7 - start_thread\n  26:     0x7fd3af7b2a2f - clone\n  27:                0x0 - <unknown>\n\"\"\"\n"},"filename":"server-framework/src/lib.rs","line_number":124,"threadName":"tokio-runtime-worker","threadId":"ThreadId(31)"}
   5:     0x556c727d1b12 - rust_begin_unwind
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   6:     0x556c71bc9a45 - core::panicking::panic_fmt::h979245e2fdb2fabd
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   7:     0x556c71c93d44 - processor::worker::Worker::run::{{closure}}::h19de3b3f89ff5ffc
   8:     0x556c71c98185 - <processor::config::IndexerGrpcProcessorConfig as server_framework::RunnableConfig>::run::{{closure}}::h8bbc3ac6bcee62e5
   9:     0x556c71c4d2a6 - <server_framework::GenericConfig<T> as server_framework::RunnableConfig>::run::{{closure}}::haa0bd3010848fb0d
  10:     0x556c71c0f204 - server_framework::run_server_with_config::{{closure}}::{{closure}}::h6cffb61b76fb2233
  11:     0x556c71c16fb2 - tokio::runtime::task::core::Core<T,S>::poll::h8d5ddcd038853453
  12:     0x556c71c092e1 - tokio::runtime::task::harness::Harness<T,S>::poll::h966f7a06296c5172
  13:     0x556c726d7c83 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h17a683d38fccdde5
  14:     0x556c726d6ece - tokio::runtime::scheduler::multi_thread::worker::Context::run::h8c6e9db5df5b45de
  15:     0x556c726dbf87 - tokio::runtime::context::scoped::Scoped<T>::set::hc23f308f5e1aa780
  16:     0x556c726dbd6f - tokio::runtime::context::runtime::enter_runtime::hcd2bb531c72feab2
  17:     0x556c726d63d8 - tokio::runtime::scheduler::multi_thread::worker::run::hcb889eaa62e3b5f1
  18:     0x556c726c4a44 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h39e0ae4677314b1e
  19:     0x556c726c6f59 - tokio::runtime::task::core::Core<T,S>::poll::hfb344e9dfb31bff4
  20:     0x556c726c241f - tokio::runtime::task::harness::Harness<T,S>::poll::h86b8fbee4d959ecd
  21:     0x556c726cb048 - tokio::runtime::blocking::pool::Inner::run::hcd49f282b0f4fc87
  22:     0x556c726e1d45 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbf1640dcb5dd63fa
  23:     0x556c726bea19 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h56f286b7e5210c94
  24:     0x556c727d4c25 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfa37c25e0ad051b0
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2007:9
                           <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9486bed8ab2e65ad
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2007:9
                           std::sys::unix::thread::Thread::new::thread_start::hd28b46dbf5673d17
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys/unix/thread.rs:108:17
  25:     0x7fd3af9deea7 - start_thread
  26:     0x7fd3af7b2a2f - clone
  27:                0x0 - <unknown>
"""
```

**Comment by larry-aptos** [comment]
we improved the processors now and it's more resilient to errors like this. let us know if this issue still existsts.
