### ISSUE TITLE
[Indexer API] Database error when getting starting version: Timed out in bb8

### ISSUE THREAD

**Issue by josedev-union** [aptos-labs/aptos-indexer-processors#617]
## Description
I run aptos indexer rust processor in K8s cluster using `aptoslabs/indexer-processor-rust:latest` image and face this error.
```sh

[Processor] Starting processor tokio runtime: num_cpus=1, worker_threads=16
{"timestamp":"2024-11-26T17:40:27.053908Z","level":"INFO","fields":{"message":"[Parser] Kicking off","processor_name":"default_processor"},"filename":"processor/src/worker.rs","line_number":160,"threadName":"tokio-runtime-worker","threadId":"ThreadId(7)"}
{"timestamp":"2024-11-26T17:40:27.054200Z","level":"INFO","fields":{"message":"[Parser] Creating connection pool","processor_name":"default_processor","service_type":"processor"},"filename":"processor/src/worker.rs","line_number":162,"threadName":"tokio-runtime-worker","threadId":"ThreadId(7)"}
{"timestamp":"2024-11-26T17:40:27.053904Z","level":"INFO","fields":{"message":"listening on http://0.0.0.0:8080"},"filename":"/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/warp-0.3.7/src/server.rs","line_number":138,"span":{"addr":"0.0.0.0:8080","name":"Server::run"},"spans":[],"threadName":"tokio-runtime-worker","threadId":"ThreadId(14)"}
{"timestamp":"2024-11-26T17:40:27.054345Z","level":"INFO","fields":{"message":"[Parser] Finish creating the connection pool","processor_name":"default_processor","service_type":"processor"},"filename":"processor/src/worker.rs","line_number":170,"threadName":"tokio-runtime-worker","threadId":"ThreadId(7)"}
{"timestamp":"2024-11-26T17:40:27.054362Z","level":"INFO","fields":{"message":"[Parser] Running migrations","processor_name":"default_processor","service_type":"processor"},"filename":"processor/src/worker.rs","line_number":214,"threadName":"tokio-runtime-worker","threadId":"ThreadId(7)"}
{"timestamp":"2024-11-26T17:40:27.054366Z","level":"INFO","fields":{"message":"Running migrations: \"postgresql://aptos-indexer:xxx@postgres.staging.svc.cluster.local:5432/aptos\""},"filename":"processor/src/worker.rs","line_number":707,"threadName":"tokio-runtime-worker","threadId":"ThreadId(7)"}
{"timestamp":"2024-11-26T17:40:27.164284Z","level":"INFO","fields":{"message":"[Parser] Finished migrations","processor_name":"default_processor","service_type":"processor","duration_in_secs":0.10991593},"filename":"processor/src/worker.rs","line_number":221,"threadName":"tokio-runtime-worker","threadId":"ThreadId(7)"}
details = """
{"timestamp":"2024-11-26T17:40:57.171707Z","level":"ERROR","fields":{"message":"details = \"\"\"\npanicked at processor/src/worker.rs:231:14:\n[Parser] Database error when getting starting version: Timed out in bb8\"\"\"\nbacktrace = \"\"\"\n   0:     0x588197321e40 - server_framework::setup_panic_handler::{{closure}}::h7eaeabd255df30e4\n   1:     0x5881979d27ff - std::panicking::rust_panic_with_hook::hfe205f6954b2c97b\n   2:     0x5881979d2427 - std::panicking::begin_panic_handler::{{closure}}::h6cb44b3a50f28c44\n   3:     0x5881979d10b9 - std::sys::backtrace::__rust_end_short_backtrace::hf1c1f2a92799bb0e\n   4:     0x5881979d20b4 - rust_begin_unwind\n   5:     0x58819669ee43 - core::panicking::panic_fmt::h3d8fc78294164da7\n   6:     0x58819669f316 - core::result::unwrap_failed::hfa79a499befff387\n   7:     0x5881969c79e8 - processor::worker::Worker::run::{{closure}}::h1b4ed1ff12d0457d\n   8:     0x5881969d209c - <processor::config::IndexerGrpcProcessorConfig as server_framework::RunnableConfig>::run::{{closure}}::h6003224f1065c959\n   9:     0x588196726a17 - <server_framework::GenericConfig<T> as server_framework::RunnableConfig>::run::{{closure}}::hd66539368868a5c8\n  10:     0x5881966b0515 - server_framework::run_server_with_config::{{closure}}::{{closure}}::h46ba048c73034d5b\n  11:     0x5881966b9e51 - tokio::runtime::task::core::Core<T,S>::poll::h73a789ccdbf719b9\n  12:     0x5881966fbc20 - tokio::runtime::task::harness::Harness<T,S>::poll::had9ac2630c5828b8\n  13:     0x5881977d8e3e - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hcef6238a764e3df2\n  14:     0x5881977d7d68 - tokio::runtime::scheduler::multi_thread::worker::Context::run::hc704cc5a57b6d6f5\n  15:     0x5881977d0556 - tokio::runtime::context::scoped::Scoped<T>::set::h55554b7b30b2fc79\n  16:     0x5881977c6f4d - tokio::runtime::context::runtime::enter_runtime::hf7ce6e899fe0b4a1\n  17:     0x5881977d6f30 - tokio::runtime::scheduler::multi_thread::worker::run::h6fc248344961c6fd\n  18:     0x5881977cb453 - tokio::runtime::task::core::Core<T,S>::poll::h54473359c83481c8\n  19:     0x5881977a8a22 - tokio::runtime::task::harness::Harness<T,S>::poll::h0359f42ceb33fc5d\n  20:     0x5881977bc1c5 - std::sys::backtrace::__rust_begin_short_backtrace::h9feccb32c90fa3e5\n  21:     0x5881977bcb62 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h18bafdf154dc2ee8\n  22:     0x5881979d571b - std::sys::pal::unix::thread::Thread::new::thread_start::ha8af9c992ef0b208\n  23:     0x7823519eaea7 - start_thread\n  24:     0x7823517beacf - clone\n  25:                0x0 - <unknown>\n\"\"\"\n"},"filename":"server-framework/src/lib.rs","line_number":133,"threadName":"tokio-runtime-worker","threadId":"ThreadId(7)"}
panicked at processor/src/worker.rs:231:14:
[Parser] Database error when getting starting version: Timed out in bb8"""
backtrace = """
   0:     0x588197321e40 - server_framework::setup_panic_handler::{{closure}}::h7eaeabd255df30e4
   1:     0x5881979d27ff - std::panicking::rust_panic_with_hook::hfe205f6954b2c97b
   2:     0x5881979d2427 - std::panicking::begin_panic_handler::{{closure}}::h6cb44b3a50f28c44
   3:     0x5881979d10b9 - std::sys::backtrace::__rust_end_short_backtrace::hf1c1f2a92799bb0e
   4:     0x5881979d20b4 - rust_begin_unwind
   5:     0x58819669ee43 - core::panicking::panic_fmt::h3d8fc78294164da7
   6:     0x58819669f316 - core::result::unwrap_failed::hfa79a499befff387
   7:     0x5881969c79e8 - processor::worker::Worker::run::{{closure}}::h1b4ed1ff12d0457d
   8:     0x5881969d209c - <processor::config::IndexerGrpcProcessorConfig as server_framework::RunnableConfig>::run::{{closure}}::h6003224f1065c959
   9:     0x588196726a17 - <server_framework::GenericConfig<T> as server_framework::RunnableConfig>::run::{{closure}}::hd66539368868a5c8
  10:     0x5881966b0515 - server_framework::run_server_with_config::{{closure}}::{{closure}}::h46ba048c73034d5b
  11:     0x5881966b9e51 - tokio::runtime::task::core::Core<T,S>::poll::h73a789ccdbf719b9
  12:     0x5881966fbc20 - tokio::runtime::task::harness::Harness<T,S>::poll::had9ac2630c5828b8
  13:     0x5881977d8e3e - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hcef6238a764e3df2
  14:     0x5881977d7d68 - tokio::runtime::scheduler::multi_thread::worker::Context::run::hc704cc5a57b6d6f5
  15:     0x5881977d0556 - tokio::runtime::context::scoped::Scoped<T>::set::h55554b7b30b2fc79
  16:     0x5881977c6f4d - tokio::runtime::context::runtime::enter_runtime::hf7ce6e899fe0b4a1
  17:     0x5881977d6f30 - tokio::runtime::scheduler::multi_thread::worker::run::h6fc248344961c6fd
  18:     0x5881977cb453 - tokio::runtime::task::core::Core<T,S>::poll::h54473359c83481c8
  19:     0x5881977a8a22 - tokio::runtime::task::harness::Harness<T,S>::poll::h0359f42ceb33fc5d
  20:     0x5881977bc1c5 - std::sys::backtrace::__rust_begin_short_backtrace::h9feccb32c90fa3e5
  21:     0x5881977bcb62 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h18bafdf154dc2ee8
  22:     0x5881979d571b - std::sys::pal::unix::thread::Thread::new::thread_start::ha8af9c992ef0b208
  23:     0x7823519eaea7 - start_thread
  24:     0x7823517beacf - clone
  25:                0x0 - <unknown>
"""
```
As you can see, db connection is ok and the migration finished correctly. But parser failed to connect db.

## Repro
- This is indexer config file.
```yaml
health_check_port: 8080
server_config:
  processor_config:
    type: default_processor
  postgres_connection_string: "postgresql://aptos-indexer:${POSTGRES_PASSWORD}@postgres.staging.svc.cluster.local:5432/aptos"
  indexer_grpc_data_service_address: "https://fullnode.mainnet.aptoslabs.com"
  auth_token: ""
```
- Image is `aptoslabs/indexer-processor-rust:latest`

**Comment by larry-aptos** [comment]
Can you try to allow insecure connection?

**Comment by larry-aptos** [comment]
Also if you go to `https://developers.aptoslabs.com/` it shows you a config to run.

in your case, I don't think `indexer_grpc_data_service_address` looks correct. 

here is a screenshot 
![image](https://github.com/user-attachments/assets/e5e77f33-12a6-46cc-bad1-ce2a4459be0f)

**Comment by josedev-union** [comment]
@larry-aptos after enabling insecure db connection, that error has been gone away.
But now it outputs another error.
```sh

{"timestamp":"2024-12-02T17:16:51.518948Z","level":"ERROR","fields":{"message":"[Parser] Error receiving datastream response for chain id","processor_name":"default_processor","service_type":"processor","stream_address":"https://fullnode.mainnet.aptoslabs.com/","connection_id":"","error":"Status { code: Internal, message: \"protocol error: received message with invalid compression flag: 85 (valid flags are 0 and 1) while receiving response with status: 401 Unauthorized\", source: None }"},"filename":"processor/src/grpc_stream.rs","line_number":276,"threadName":"tokio-runtime-worker","threadId":"ThreadId(15)"}
details = """
panicked at processor/src/grpc_stream.rs:284:13:
[Parser] Error receiving datastream response for chain id"""
backtrace = """
   0:     0x5ccaefaaee40 - server_framework::setup_panic_handler::{{closure}}::h7eaeabd255df30e4
   1:     0x5ccaf015f7ff - std::panicking::rust_panic_with_hook::hfe205f6954b2c97b
   2:     0x5ccaf015f3f3 - std::panicking::begin_panic_handler::{{closure}}::h6cb44b3a50f28c44
   3:     0x5ccaf015e0b9 - std::sys::backtrace::__rust_end_short_backtrace::hf1c1f2a92799bb0e
   4:     0x5ccaf015f0b4 - rust_begin_unwind
   5:     0x5ccaeee2be43 - core::panicking::panic_fmt::h3d8fc78294164da7
   6:     0x5ccaef1555df - processor::worker::Worker::run::{{closure}}::h1b4ed1ff12d0457d
   7:     0x5ccaef15f09c - <processor::config::IndexerGrpcProcessorConfig as server_framework::RunnableConfig>::run::{{closure}}::h6003224f1065c959
   8:     0x5ccaeeeb3a17 - <server_framework::GenericConfig<T> as server_framework::RunnableConfig>::run::{{closure}}::hd66539368868a5c8
   9:     0x5ccaeee3d515 - server_framework::run_server_with_config::{{closure}}::{{closure}}::h46ba048c73034d5b
  10:     0x5ccaeee46e51 - tokio::runtime::task::core::Core<T,S>::poll::h73a789ccdbf719b9
  11:     0x5ccaeee88c20 - tokio::runtime::task::harness::Harness<T,S>::poll::had9ac2630c5828b8
  12:     0x5ccaeff65e3e - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hcef6238a764e3df2
  13:     0x5ccaeff64d68 - tokio::runtime::scheduler::multi_thread::worker::Context::run::hc704cc5a57b6d6f5
  14:     0x5ccaeff5d556 - tokio::runtime::context::scoped::Scoped<T>::set::h55554b7b30b2fc79
  15:     0x5ccaeff53f4d - tokio::runtime::context::runtime::enter_runtime::hf7ce6e899fe0b4a1
  16:     0x5ccaeff63f30 - tokio::runtime::scheduler::multi_thread::worker::run::h6fc248344961c6fd
  17:     0x5ccaeff58453 - tokio::runtime::task::core::Core<T,S>::poll::h54473359c83481c8
  18:     0x5ccaeff35a22 - tokio::runtime::task::harness::Harness<T,S>::poll::h0359f42ceb33fc5d
  19:     0x5ccaeff491c5 - std::sys::backtrace::__rust_begin_short_backtrace::h9feccb32c90fa3e5
  20:     0x5ccaeff49b62 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h18bafdf154dc2ee8
  21:     0x5ccaf016271b - std::sys::pal::unix::thread::Thread::new::thread_start::ha8af9c992ef0b208
  22:     0x7c0291db9ea7 - start_thread
  23:     0x7c0291b8dacf - clone
  24:                0x0 - <unknown>
"""

{"timestamp":"2024-12-02T17:16:51.525019Z","level":"ERROR","fields":{"message":"details = \"\"\"\npanicked at processor/src/grpc_stream.rs:284:13:\n[Parser] Error receiving datastream response for chain id\"\"\"\nbacktrace = \"\"\"\n   0:     0x5ccaefaaee40 - server_framework::setup_panic_handler::{{closure}}::h7eaeabd255df30e4\n   1:     0x5ccaf015f7ff - std::panicking::rust_panic_with_hook::hfe205f6954b2c97b\n   2:     0x5ccaf015f3f3 - std::panicking::begin_panic_handler::{{closure}}::h6cb44b3a50f28c44\n   3:     0x5ccaf015e0b9 - std::sys::backtrace::__rust_end_short_backtrace::hf1c1f2a92799bb0e\n   4:     0x5ccaf015f0b4 - rust_begin_unwind\n   5:     0x5ccaeee2be43 - core::panicking::panic_fmt::h3d8fc78294164da7\n   6:     0x5ccaef1555df - processor::worker::Worker::run::{{closure}}::h1b4ed1ff12d0457d\n   7:     0x5ccaef15f09c - <processor::config::IndexerGrpcProcessorConfig as server_framework::RunnableConfig>::run::{{closure}}::h6003224f1065c959\n   8:     0x5ccaeeeb3a17 - <server_framework::GenericConfig<T> as server_framework::RunnableConfig>::run::{{closure}}::hd66539368868a5c8\n   9:     0x5ccaeee3d515 - server_framework::run_server_with_config::{{closure}}::{{closure}}::h46ba048c73034d5b\n  10:     0x5ccaeee46e51 - tokio::runtime::task::core::Core<T,S>::poll::h73a789ccdbf719b9\n  11:     0x5ccaeee88c20 - tokio::runtime::task::harness::Harness<T,S>::poll::had9ac2630c5828b8\n  12:     0x5ccaeff65e3e - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hcef6238a764e3df2\n  13:     0x5ccaeff64d68 - tokio::runtime::scheduler::multi_thread::worker::Context::run::hc704cc5a57b6d6f5\n  14:     0x5ccaeff5d556 - tokio::runtime::context::scoped::Scoped<T>::set::h55554b7b30b2fc79\n  15:     0x5ccaeff53f4d - tokio::runtime::context::runtime::enter_runtime::hf7ce6e899fe0b4a1\n  16:     0x5ccaeff63f30 - tokio::runtime::scheduler::multi_thread::worker::run::h6fc248344961c6fd\n  17:     0x5ccaeff58453 - tokio::runtime::task::core::Core<T,S>::poll::h54473359c83481c8\n  18:     0x5ccaeff35a22 - tokio::runtime::task::harness::Harness<T,S>::poll::h0359f42ceb33fc5d\n  19:     0x5ccaeff491c5 - std::sys::backtrace::__rust_begin_short_backtrace::h9feccb32c90fa3e5\n  20:     0x5ccaeff49b62 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h18bafdf154dc2ee8\n  21:     0x5ccaf016271b - std::sys::pal::unix::thread::Thread::new::thread_start::ha8af9c992ef0b208\n  22:     0x7c0291db9ea7 - start_thread\n  23:     0x7c0291b8dacf - clone\n  24:                0x0 - <unknown>\n\"\"\"\n"},"filename":"server-framework/src/lib.rs","line_number":133,"threadName":"tokio-runtime-worker","threadId":"ThreadId(15)"}

```

**Comment by larry-aptos** [comment]
401 Unauthorized: you need to attach your auth token. You can get from
developers.aptoslabs.com

**Comment by larry-aptos** [comment]
Let me know if you have other questions; I'm going to close the issue.
